recipe: default.v1
language: en

assistant_id: klm_upgrade_skill

pipeline:
  - name: SearchReadyLLMCommandGenerator
    llm:
      model: gpt-4o-mini
      request_timeout: 30

policies:
  - name: FlowPolicy
  - name: EnterpriseSearchPolicy
    prompt_template: prompt_templates/enterprise-search-template.jinja2
    vector_store:
      type: faiss
      embeddings:
        model_name: text-embedding-3-small
